### ISSUE TITLE
Failure downloading nif-text-links

### ISSUE THREAD

**Issue by Khorda** [NLP2RDF/DBpediaOpenDBpediaTextExtractionChallenge#6]
Could you please check and correct **DBpediaOpenDBpediaTextExtractionChallenge/docker/install.sh**

At line 28 there is a space in the _wget_ argument (last char before the double quote) that breaks the download process.

Thank you

**Comment by sandroacoelho** [comment]
Hi @Khorda,

Thank you for the feedback and patience. I fixed it. Could you please try again?

Best,
